### ISSUE TITLE
cache is not saved. when refreshing the page, the data is gone.

### ISSUE THREAD

**Issue by bigoper** [dirkbonhomme/js-cache#2]
Vue.http.interceptors.push(
  function(request, next) {

    console.log('cache.debug',cache.debug());
    //Print current request
    console.log("MAIN.JS REQUEST", request);

    let cacheKey = `CACHE_${request.url}`;
    cacheKey = _.split(cacheKey, '/');
    cacheKey = _.join(cacheKey, '_');
    cacheKey = _.camelCase(cacheKey);;

    console.log('cacheKey',cacheKey);
    console.log('cacheKey',cache.get(cacheKey));

    // Check if GET request
    if(request.method.toLowerCase() === 'get') {

      let _cache = cache.get(cacheKey);

      if (_cache) {
        console.log('cache hit', cacheKey);

        next( (response) => {

          let {status, statusText, body} = response;

          if (status === 200 && request.method.toLowerCase() === 'get') {

            console.log('cache save', cacheKey);
            console.log('cacheKey',cacheKey);
            cache.set(cacheKey, body, 60000);

            console.log(cache.get('lorem'));

          }

        });

      } else {
        console.log('cache miss', cacheKey);
      }

    }

    // continue to next interceptor
    next( (response) => {

      let {status, statusText, body} = response;

      if (status === 200 && request.method.toLowerCase() === 'get') {

        console.log('cache save', cacheKey);
        console.log('cacheKey',cacheKey);
        cache.set(cacheKey, body, 60000);

        console.log(cache.get('lorem'));

      }

    });
  }
);

**Comment by dirkbonhomme** [comment]
Hi @bigoper 

This library is only meant as an in-memory store and will indeed lose data after refresh. You could try to implement handlers that write to the `localStorage` or `sessionStorage` https://github.com/dirkbonhomme/js-cache#external-data-source
